services:
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DB_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5080:80"
      - "5443:443"
    networks:
      - reversi-network
    env_file:
      - ../reversi-server/data-base/.env
    volumes:
      - pgadmin:/var/lib/pgadmin

  database:
    container_name: reversi
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PG_DATA: "database:/data/postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - database:/data/postgres
    ports:
      - "5431:5432"
    restart: always
    networks:
      - reversi-network
    env_file:
      - ../reversi-server/data-base/.env

volumes:
  database:
  pgadmin:

networks:
  reversi-network:
    driver: bridge